CREATE SEQUENCE IF NOT EXISTS student_id_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE student
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,

    CONSTRAINT pk_students PRIMARY KEY (id)
);


CREATE SEQUENCE IF NOT EXISTS course_id_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE course
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(100) NOT NULL UNIQUE,
    teacher_id BIGINT,

    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE students_courses
(
    student_id BIGINT NOT NULL,
    course_id  BIGINT NOT NULL,

    CONSTRAINT unique_student_course UNIQUE (student_id, course_id)
);


CREATE SEQUENCE IF NOT EXISTS teacher_id_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE teacher
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(50) NOT NULL,
    department_id BIGINT,

    CONSTRAINT pk_teachers PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS department_id_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE department
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR(50) NOT NULL UNIQUE,
    head_of_department_id BIGINT,

    CONSTRAINT pk_department PRIMARY KEY (id)
);

ALTER TABLE students_courses
    ADD CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE;

ALTER TABLE course
    ADD CONSTRAINT fk_teacher FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE;

ALTER TABLE teacher
    ADD CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE;

ALTER TABLE department
    ADD CONSTRAINT fk_teacher FOREIGN KEY (head_of_department_id) REFERENCES teacher (id) ON DELETE CASCADE;