openapi: 3.1.0
info:
  title: Data transfer objects
  version: 0.0.1

paths: {}

components:
  schemas:

    CourseCreateRq:
      type: object
      required: [title]
      properties:
        title:
          type: string
          maxLength: 255

    CourseShortDto:
      type: object
      required: [id, title]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          maxLength: 255
        teacher:
          $ref: '#/components/schemas/TeacherShortDto'
          nullable: true

    CourseBasicDto:
      type: object
      required: [ id, title ]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          maxLength: 255


    CourseDto:
      type: object
      required: [id, title]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          maxLength: 255
        teacher:
          $ref: '#/components/schemas/TeacherShortDto'
          nullable: true
        students:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/StudentShortDto'
          nullable: true
          default: []

    DepartmentCreateRq:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 255

    DepartmentShortDto:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255

    DepartmentDto:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255
        headOfDepartment:
          $ref: '#/components/schemas/TeacherShortDto'
          nullable: true

    StudentCreateRq:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
          maxLength: 255
        email:
          type: string
          format: email

    StudentUpdateRq:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        email:
          type: string
          format: email

    StudentShortDto:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255

    StudentDto:
      type: object
      required: [id, name, email]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255
        email:
          type: string
          format: email
        courses:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CourseShortDto'
          nullable: true
          default: []

    TeacherCreateRq:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 255

    TeacherShortDto:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255

    TeacherDto:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255
        courses:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CourseBasicDto'
          nullable: true
          default: []
        department:
          $ref: '#/components/schemas/DepartmentShortDto'
          nullable: true

    ExceptionResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - timestamp
        - status
        - error
        - message
        - path